/**
 * Pipeline step 6 (deploy-cli.md § The pipeline; design-notes.md's "Driving
 * Alchemy" call): writes a small, human-readable, regenerated-every-run stack
 * module at `.makerkit/alchemy.run.ts` inside the entry module's package dir.
 * It calls `lower()` with the values the CLI already computed — no logic of
 * its own, so it stays independently runnable (`alchemy deploy
 * .makerkit/alchemy.run.ts`) to bisect a CLI bug from an Alchemy bug.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { AssembledServices } from './assemble-services.ts';

export interface StackFileInput {
  /** Absolute path to the entry module (the app's default-exported node). */
  readonly entryPath: string;
  /** The entry module's package dir — where `.makerkit/` is written. */
  readonly entryPkgDir: string;
  /** The pack package name whose `/target` supplies `fromEnv()`. */
  readonly pack: string;
  readonly name: string;
  readonly stage: string | undefined;
  readonly assembled: AssembledServices;
}

const GENERATED_DIR = '.makerkit';
const GENERATED_FILE = 'alchemy.run.ts';

/** A relative import specifier from `.makerkit/alchemy.run.ts` to `target`. */
function relativeImportSpecifier(generatedDir: string, target: string): string {
  const rel = path.relative(generatedDir, target).split(path.sep).join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function renderBundle(bundle: { dir: string; entry: string }): string {
  return `{ dir: ${quote(bundle.dir)}, entry: ${quote(bundle.entry)} }`;
}

function renderOptions(input: StackFileInput): string {
  const lines: string[] = [];
  lines.push(`  name: ${quote(input.name)},`);
  if (input.stage !== undefined) lines.push(`  stage: ${quote(input.stage)},`);

  if (input.assembled.bundle !== undefined) {
    lines.push(`  bundle: ${renderBundle(input.assembled.bundle)},`);
  } else if (input.assembled.bundles !== undefined) {
    lines.push('  bundles: {');
    for (const [id, bundle] of Object.entries(input.assembled.bundles)) {
      lines.push(`    ${quote(id)}: ${renderBundle(bundle)},`);
    }
    lines.push('  },');
  }

  return lines.join('\n');
}

/** Renders the stack module's source — exported separately so tests can assert on its content without touching disk. */
export function renderStackFile(input: StackFileInput): string {
  const generatedDir = path.join(input.entryPkgDir, GENERATED_DIR);
  const appImport = relativeImportSpecifier(generatedDir, input.entryPath);

  return `/**
 * Generated by \`makerkit deploy\`/\`makerkit destroy\` — overwritten on every
 * run; do not edit by hand. Independently runnable from ${quote(input.entryPkgDir)}:
 *
 *   alchemy deploy ${GENERATED_DIR}/${GENERATED_FILE}
 *
 * bisects a CLI bug from an Alchemy bug (deploy-cli.md § Implementation decisions).
 */
import { lower } from '@makerkit/core/deploy';
import { fromEnv } from ${quote(`${input.pack}/target`)};
import app from ${quote(appImport)};

export default lower(app, fromEnv(), {
${renderOptions(input)}
});
`;
}

/** Writes the stack file, returning its absolute path. */
export function writeStackFile(input: StackFileInput): string {
  const generatedDir = path.join(input.entryPkgDir, GENERATED_DIR);
  fs.mkdirSync(generatedDir, { recursive: true });
  const filePath = path.join(generatedDir, GENERATED_FILE);
  fs.writeFileSync(filePath, renderStackFile(input));
  return filePath;
}

export const GENERATED_STACK_RELATIVE_PATH = path.join(GENERATED_DIR, GENERATED_FILE);
